name: escrow_app
description: A modern and minimal mobile app MVP for contract escrow system.
publish_to: "none"
# version: 1.0.4
version: 1.0.0+10

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Firebase Core
  firebase_core: ^3.13.1
  # Firebase Authentication
  firebase_auth: ^5.5.4
  # Cloud Firestore
  cloud_firestore: ^5.6.8
  # Firebase Storage
  firebase_app_check: ^0.3.2+6
  firebase_messaging: ^15.2.6
  googleapis_auth: ^2.0.0
  flutter_local_notifications: ^17.1.2
  webview_flutter: ^4.7.0
  url_launcher: ^6.2.5
  random_avatar: ^0.0.8
  rich_field_controller: ^0.2.1
  package_info_plus: ^4.0.0
  dio: ^5.0.0

  http: ^1.4.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  uuid: ^4.3.3
  intl: ^0.20.2
  share_plus: ^11.0.0
  google_fonts: ^6.1.0
  iconsax: ^0.0.8
  permission_handler: ^11.0.1
  path_provider: ^2.1.2
  flutter_contacts: ^1.1.7
  in_app_update: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#00FF00"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
 

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 100
